### ISSUE TITLE
Would you mind to give an instruction about how to reproduce your results?

### ISSUE THREAD

**Issue by D-X-Y** [chenyuntc/dsod.pytorch#1]
Hi, I'm very surprised by your results and interested in your implementation.
I notice that you provide the trained models FPNSSD512.
Would you mind to give an instruction on how to train FPNSSD512 using your codes?

Thanks very much for your help.

**Comment by chenyuntc** [comment]
Sorry, you are mislead!
The results in readme are SSD from torchcv, I haven't implemented it yet!!!
Code could be found in `examples/dsod` and `torchcv/models/dsod`. I'll update readme!
